[tool.pytest.ini_options]
addopts = "-rsxX -l -v --tb=short --alluredir=./results --clean-alluredir"
testpaths = ["tests"]

log_cli = true
log_cli_level = "INFO"
log_level= "INFO"
log_format = "[%(asctime)s.%(msecs)03d] - %(levelname)s -  %(message)s"
log_cli_format = "[%(asctime)s.%(msecs)03d] - %(levelname)s - %(message)s"
log_date_format =  "%H:%M:%S"
log_cli_date_format = "%H:%M:%S"
